#ifndef _CONFIG_H_
#define _CONFIG_H_

#define TILE_SIZE 10
#define MAP_WIDTH 64
#define MAP_HEIGHT 32

#define WALL_COLOR_RED 128
#define WALL_COLOR_GREEN 128
#define WALL_COLOR_BLUE 128

#define SNAKE_COLOR_RED 255
#define SNAKE_COLOR_GREEN 255
#define SNAKE_COLOR_BLUE 255

#define SNAKE_HEAD_COLOR_RED 0
#define SNAKE_HEAD_COLOR_GREEN 255
#define SNAKE_HEAD_COLOR_BLUE 0

#define FRUIT_COLOR_RED 128
#define FRUIT_COLOR_GREEN 0
#define FRUIT_COLOR_BLUE 0

#endif
